
/*
 Group Name: TuffyBase
 Team Lead: Diana Maldonado: { di.maldonado5504@csu.fullerton.edu }
 Group Members:
 Dylan Morales: { d.morales7241@csu.fullerton.edu } Nikita Subedi: { 22subedin@csu.fullerton.edu }
*/



-- Run this script directly in the MySQL server query window it will automatically create the database and all the database objects.
-- Creating Company Schema
DROP DATABASE IF EXISTS ABC_Entertainment_Company_db;
CREATE DATABASE ABC_Entertainment_Company_db;


USE ABC_Entertainment_Company_db;

DROP TABLE IF EXISTS CINEMA;
CREATE TABLE CINEMA (
    Cinema_Id       INT,
    Name            VARCHAR(100) NOT NULL,
    Street_no       VARCHAR(10),
    Street_name     VARCHAR(50),
    City            VARCHAR(50),
    State           VARCHAR(50),
    ZIP_code        VARCHAR(10),
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cinema 
        PRIMARY KEY (Cinema_Id)
);

DROP TABLE IF EXISTS AUDITORIUM;
CREATE TABLE AUDITORIUM (
    Auditorium_Id   INT,
    Name            VARCHAR(50),
    Capacity        INT NOT NULL,
    Support_3D      BIT,
    Support_IMAX    BIT,
    Cinema_Id       INT NOT NULL,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auditorium 
        PRIMARY KEY (Auditorium_Id),
    CONSTRAINT uk_Aname UNIQUE (Name), 
    CONSTRAINT fk_auditorium_cinema
        FOREIGN KEY (Cinema_Id) REFERENCES CINEMA(Cinema_Id)
);

DROP TABLE IF EXISTS SEAT;
CREATE TABLE SEAT (
    Seat_Id         INT,
    Row_no          VARCHAR(5),
    Seat_no         VARCHAR(5),
    Auditorium_Id   INT NOT NULL,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_seat 
        PRIMARY KEY (Seat_Id),
    CONSTRAINT fk_seat_auditorium
        FOREIGN KEY (Auditorium_Id) REFERENCES AUDITORIUM(Auditorium_Id)
);

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
    Employee_Id     INT UNIQUE,
    Fname           VARCHAR(50) NOT NULL,
    Lname           VARCHAR(50) NOT NULL,
    Phone_no        VARCHAR(20),
    Street_no       VARCHAR(10),
    Street_name     VARCHAR(50),
    City            VARCHAR(50),
    State           VARCHAR(50),
    ZIP_code        VARCHAR(10),
    Email           VARCHAR(100) UNIQUE,
    Cinema_Id       INT,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_employee 
        PRIMARY KEY (Employee_Id),
    CONSTRAINT fk_employee_cinema 
        FOREIGN KEY (Cinema_Id) REFERENCES CINEMA(Cinema_Id)
);

DROP TABLE IF EXISTS USER_ACCOUNT;
CREATE TABLE USER_ACCOUNT (
    Username      VARCHAR(50),
    Employee_Id   INT NOT NULL,
    Password_Hash VARCHAR(255) NOT NULL,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user 
        PRIMARY KEY (Username),
    CONSTRAINT fk_user_employee 
        FOREIGN KEY (Employee_Id) REFERENCES EMPLOYEE(Employee_Id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
); 


DROP TABLE IF EXISTS ROLES;
CREATE TABLE ROLES (
    Role_Id         INT,
    Role_Name       VARCHAR(100) NOT NULL UNIQUE,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_roles 
        PRIMARY KEY (Role_Id)
);

DROP TABLE IF EXISTS PERFORMS;
CREATE TABLE PERFORMS (
    Employee_Id     INT,
    Role_Id         INT,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_performs 
        PRIMARY KEY (Employee_Id, Role_Id),
    CONSTRAINT fk_performs 
        FOREIGN KEY (Employee_Id) REFERENCES EMPLOYEE(Employee_Id),
        FOREIGN KEY (Role_Id) REFERENCES ROLES(Role_Id)
);

DROP TABLE IF EXISTS RATING;
CREATE TABLE RATING (
    Rate_Id         INT,
    Rating          VARCHAR(10) NOT NULL,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_rating 
        PRIMARY KEY (Rate_Id)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (
    Genre_Id        INT,
    Genre_type      VARCHAR(50) NOT NULL,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_genres
        PRIMARY KEY (Genre_Id)
);

DROP TABLE IF EXISTS MOVIE;
CREATE TABLE MOVIE (
    Movie_Id        INT,
    Title           VARCHAR(255) NOT NULL,
    Description     TEXT,
    Year            INT,
    Duration        INT,
    Release_Date    DATE,
    Rate_Id         INT,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_movie
        PRIMARY KEY (Movie_Id),
    CONSTRAINT fk_movie_rating
        FOREIGN KEY (Rate_Id) REFERENCES RATING(Rate_Id)
);

DROP TABLE IF EXISTS MOVIE_GENRE;
CREATE TABLE MOVIE_GENRE (
    Movie_Id        INT,
    Genre_Id        INT,
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_movie_genre
        PRIMARY KEY (Movie_Id, Genre_Id),
    CONSTRAINT fk_movie_genre
        FOREIGN KEY (Movie_Id) REFERENCES MOVIE(Movie_Id),
        FOREIGN KEY (Genre_Id) REFERENCES GENRES(Genre_Id)
);

DROP TABLE IF EXISTS SHOWS;
CREATE TABLE SHOWS (
    Auditorium_Id   INT,
    Movie_Id        INT,
    Start_time      DATETIME NOT NULL,
    End_time        DATETIME NOT NULL,
    Format          VARCHAR(20),
    Creation_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_shows
        PRIMARY KEY (Auditorium_Id, Movie_Id, Start_time),
    CONSTRAINT fk_shows
        FOREIGN KEY (Auditorium_Id) REFERENCES AUDITORIUM(Auditorium_Id),
        FOREIGN KEY (Movie_Id) REFERENCES MOVIE(Movie_Id)
);

-- VIEWS --

-- V1: Long Movies by Genre
CREATE VIEW Long_Movies_By_Genre AS
SELECT 
    g.Genre_type AS Genre,
    c.Name AS Cinema_Name,
    a.Name AS Auditorium_Name,
    m.Title AS Movie_Title,
    m.Duration
FROM MOVIE m
JOIN MOVIE_GENRE mg 
    ON m.Movie_Id = mg.Movie_Id
JOIN GENRES g 
    ON mg.Genre_Id = g.Genre_Id
JOIN SHOWS s 
    ON m.Movie_Id = s.Movie_Id
JOIN AUDITORIUM a 
    ON s.Auditorium_Id = a.Auditorium_Id
JOIN CINEMA c 
    ON a.Cinema_Id = c.Cinema_Id
WHERE m.Duration > 120
ORDER BY g.Genre_type, c.Name, a.Name, m.Title;


-- V2: 3D Screenings
CREATE OR REPLACE VIEW Cinema_3D_Screens AS
SELECT 
    c.Name AS Cinema_Name,
    CONCAT(c.Street_no, ' ', c.Street_name, ', ', c.City, ', ', c.State, ' ', c.ZIP_code) AS Address,
    a.Name AS Auditorium_Name,
    a.Capacity,
    a.Support_3D
FROM CINEMA c
JOIN AUDITORIUM a 
    ON c.Cinema_Id = a.Cinema_Id
WHERE a.Support_3D = 1
ORDER BY c.Name, a.Name;


-- V3: Movies shown >3x
CREATE OR REPLACE VIEW Movies_Shown_More_Than_3_Times AS
SELECT 
    m.Title AS Movie_Title,
    s.Movie_Id,
    DATE(s.Start_time) AS Show_Date,
    COUNT(*) AS Show_Count
FROM SHOWS s
JOIN MOVIE m 
    ON s.Movie_Id = m.Movie_Id
GROUP BY s.Movie_Id, DATE(s.Start_time)
HAVING COUNT(*) > 3
ORDER BY Show_Date, m.Title;



-- Insert records

-- INSERT INTO CINEMA (Cinema_Id, Name, Street_no, Street_name, City, State, ZIP_code, Creation_Time) 
INSERT INTO CINEMA VALUES (1, 'Universe Cinemas',  '10A', 'Sunset Blvd',     'Los Angeles', 'CA', '70005', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (2, 'Moonplex',          '11B', 'Elm Street',      'Dallas',      'TX', '70007', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (3, 'Starlight Theatre', '220', 'Camelback Road',  'Phoenix',     'AZ', '85001', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (4, 'Galaxy Point',      '87',  'Pine Street',     'Seattle',     'WA', '98101', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (5, 'CineNova',          '15C', 'Colfax Avenue',   'Denver',      'CO', '80202', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (6, 'SilverScreen Hub',  '440', 'Ocean Drive',     'Miami',       'FL', '33101', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (7, 'Horizon Movies',    '72A', 'Michigan Avenue', 'Chicago',     'IL', '60601', CURRENT_TIMESTAMP);
INSERT INTO CINEMA VALUES (8, 'Aurora Cinemas',    '301', 'Broadway',        'New York',    'NY', '10001', CURRENT_TIMESTAMP);


-- INSERT INTO AUDITORIUM (Auditorium_Id, Name, Capacity, Support_3D, Support_IMAX, Cinema_Id, Creation_Time) VALUES
INSERT INTO AUDITORIUM VALUES (101, 'Real Hall',         170, 1, 0, 1, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (102, 'IMAX Dome',         210, 1, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (103, 'Galaxy Room',       140, 1, 0, 1, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (104, 'Nova Screen',       185, 0, 0, 1, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (105, 'Sunset Chamber',    120, 1, 0, 1, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (106, 'Blue Horizon',      200, 1, 1, 2, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (107, 'Lunar Theatre',     155, 1, 0, 2, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (108, 'Stardust Hall',     180, 0, 0, 2, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (109, 'Phoenix Arena',     160, 1, 0, 3, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (110, 'Camelback Hall',    130, 0, 0, 3, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (111, 'Red Rock IMAX',     220, 1, 1, 3, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (112, 'Emerald Screen',    145, 1, 0, 4, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (113, 'Pacific Ultra',     190, 1, 1, 4, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (114, 'Pinewood Stage',    110, 0, 0, 4, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (115, 'Colfax Hall',       175, 1, 0, 5, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (116, 'Denver Prime',      200, 1, 1, 5, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (117, 'Rocky Ridge Room',  125, 0, 0, 5, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (118, 'Miami Bay Screen',  160, 1, 0, 6, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (119, 'OceanView IMAX',    230, 1, 1, 6, CURRENT_TIMESTAMP);
INSERT INTO AUDITORIUM VALUES (120, 'Tropics Stage',     135, 0, 0, 6, CURRENT_TIMESTAMP);


-- INSERT INTO SEAT (Seat_Id, Row_no, Seat_no, Auditorium_Id, Creation_Time) VALUES
INSERT INTO SEAT VALUES (1,  'A', '01', 101, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 101
INSERT INTO SEAT VALUES (2,  'A', '02', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (3,  'A', '03', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (4,  'A', '04', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (5,  'B', '01', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (6,  'B', '02', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (7,  'B', '03', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (8,  'C', '01', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (9,  'C', '02', 101, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (10, 'C', '03', 101, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (11, 'A', '01', 102, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 102
INSERT INTO SEAT VALUES (12, 'A', '02', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (13, 'A', '03', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (14, 'A', '04', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (15, 'B', '01', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (16, 'B', '02', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (17, 'B', '03', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (18, 'C', '01', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (19, 'C', '02', 102, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (20, 'C', '03', 102, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (21, 'A', '01', 103, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 103
INSERT INTO SEAT VALUES (22, 'A', '02', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (23, 'A', '03', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (24, 'A', '04', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (25, 'B', '01', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (26, 'B', '02', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (27, 'B', '03', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (28, 'C', '01', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (29, 'C', '02', 103, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (30, 'C', '03', 103, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (31, 'A', '01', 104, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 104
INSERT INTO SEAT VALUES (32, 'A', '02', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (33, 'A', '03', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (34, 'A', '04', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (35, 'B', '01', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (36, 'B', '02', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (37, 'B', '03', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (38, 'C', '01', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (39, 'C', '02', 104, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (40, 'C', '03', 104, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (41, 'A', '01', 105, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 105
INSERT INTO SEAT VALUES (42, 'A', '02', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (43, 'A', '03', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (44, 'A', '04', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (45, 'B', '01', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (46, 'B', '02', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (47, 'B', '03', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (48, 'C', '01', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (49, 'C', '02', 105, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (50, 'C', '03', 105, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (51, 'A', '01', 106, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 106
INSERT INTO SEAT VALUES (52, 'A', '02', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (53, 'A', '03', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (54, 'A', '04', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (55, 'B', '01', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (56, 'B', '02', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (57, 'B', '03', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (58, 'C', '01', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (59, 'C', '02', 106, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (60, 'C', '03', 106, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (61, 'A', '01', 107, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 107
INSERT INTO SEAT VALUES (62, 'A', '02', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (63, 'A', '03', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (64, 'A', '04', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (65, 'B', '01', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (66, 'B', '02', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (67, 'B', '03', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (68, 'C', '01', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (69, 'C', '02', 107, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (70, 'C', '03', 107, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (71, 'A', '01', 108, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 108
INSERT INTO SEAT VALUES (72, 'A', '02', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (73, 'A', '03', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (74, 'A', '04', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (75, 'B', '01', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (76, 'B', '02', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (77, 'B', '03', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (78, 'C', '01', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (79, 'C', '02', 108, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (80, 'C', '03', 108, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (81, 'A', '01', 109, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 109
INSERT INTO SEAT VALUES (82, 'A', '02', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (83, 'A', '03', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (84, 'A', '04', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (85, 'B', '01', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (86, 'B', '02', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (87, 'B', '03', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (88, 'C', '01', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (89, 'C', '02', 109, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (90, 'C', '03', 109, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES ( 91, 'A', '01', 110, CURRENT_TIMESTAMP);   -- SEATS FOR AUDITORIUM 110
INSERT INTO SEAT VALUES ( 92, 'A', '02', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 93, 'A', '03', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 94, 'A', '04', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 95, 'B', '01', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 96, 'B', '02', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 97, 'B', '03', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 98, 'C', '01', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES ( 99, 'C', '02', 110, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (100, 'C', '03', 110, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (101, 'A', '01', 111, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 111
INSERT INTO SEAT VALUES (102, 'A', '02', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (103, 'A', '03', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (104, 'A', '04', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (105, 'B', '01', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (106, 'B', '02', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (107, 'B', '03', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (108, 'C', '01', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (109, 'C', '02', 111, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (110, 'C', '03', 111, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (111, 'A', '01', 112, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 112
INSERT INTO SEAT VALUES (112, 'A', '02', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (113, 'A', '03', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (114, 'A', '04', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (115, 'B', '01', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (116, 'B', '02', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (117, 'B', '03', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (118, 'C', '01', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (119, 'C', '02', 112, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (120, 'C', '03', 112, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (121, 'A', '01', 113, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 113
INSERT INTO SEAT VALUES (122, 'A', '02', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (123, 'A', '03', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (124, 'A', '04', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (125, 'B', '01', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (126, 'B', '02', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (127, 'B', '03', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (128, 'C', '01', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (129, 'C', '02', 113, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (130, 'C', '03', 113, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (131, 'A', '01', 114, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 114
INSERT INTO SEAT VALUES (132, 'A', '02', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (133, 'A', '03', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (134, 'A', '04', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (135, 'B', '01', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (136, 'B', '02', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (137, 'B', '03', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (138, 'C', '01', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (139, 'C', '02', 114, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (140, 'C', '03', 114, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (141, 'A', '01', 115, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 115
INSERT INTO SEAT VALUES (142, 'A', '02', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (143, 'A', '03', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (144, 'A', '04', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (145, 'B', '01', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (146, 'B', '02', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (147, 'B', '03', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (148, 'C', '01', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (149, 'C', '02', 115, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (150, 'C', '03', 115, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (151, 'A', '01', 116, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 116
INSERT INTO SEAT VALUES (152, 'A', '02', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (153, 'A', '03', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (154, 'A', '04', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (155, 'B', '01', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (156, 'B', '02', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (157, 'B', '03', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (158, 'C', '01', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (159, 'C', '02', 116, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (160, 'C', '03', 116, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (161, 'A', '01', 117, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 117
INSERT INTO SEAT VALUES (162, 'A', '02', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (163, 'A', '03', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (164, 'A', '04', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (165, 'B', '01', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (166, 'B', '02', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (167, 'B', '03', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (168, 'C', '01', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (169, 'C', '02', 117, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (170, 'C', '03', 117, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (171, 'A', '01', 118, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 118
INSERT INTO SEAT VALUES (172, 'A', '02', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (173, 'A', '03', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (174, 'A', '04', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (175, 'B', '01', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (176, 'B', '02', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (177, 'B', '03', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (178, 'C', '01', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (179, 'C', '02', 118, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (180, 'C', '03', 118, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (181, 'A', '01', 119, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 119
INSERT INTO SEAT VALUES (182, 'A', '02', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (183, 'A', '03', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (184, 'A', '04', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (185, 'B', '01', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (186, 'B', '02', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (187, 'B', '03', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (188, 'C', '01', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (189, 'C', '02', 119, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (190, 'C', '03', 119, CURRENT_TIMESTAMP);

INSERT INTO SEAT VALUES (191, 'A', '01', 120, CURRENT_TIMESTAMP);  -- SEATS FOR AUDITORIUM 120
INSERT INTO SEAT VALUES (192, 'A', '02', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (193, 'A', '03', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (194, 'A', '04', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (195, 'B', '01', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (196, 'B', '02', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (197, 'B', '03', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (198, 'C', '01', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (199, 'C', '02', 120, CURRENT_TIMESTAMP);
INSERT INTO SEAT VALUES (200, 'C', '03', 120, CURRENT_TIMESTAMP);


-- INSERT INTO EMPLOYEE (Employee_Id, Fname, Lname, Phone_no, Street_no, Street_name, City, State, ZIP_code, Email, Cinema_Id, Creation_Time) 
INSERT INTO EMPLOYEE VALUES (1,  'Aly',      'Paul',     '555-123-8888', '12A',  'Cypress Ave', 'Los Angeles',  'CA', '70005', 'aly.paul@company.com',         1, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (3,  'John',     'Peters',   '555-000-0000', '123',  'Cypess St',   'Dalls',        'TX', '70007', 'john.peters@company.com',      1, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (2,  'Bill',     'Smith',    '555-567-9999', '45B',  'Pacific Ave', 'Dallas',       'TX', '70007', 'bill.smith@company.com',       2, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (4,  'Bob',      'Bender',   '666-665-6000', '8794', 'Garfield',    'Chicago',      'IL', '90210', 'bob.bender@company.com',       8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (5,  'Kim',      'Grace',    '633-335-3000', '6677', 'Mills Ave',   'Sacramento',   'CA', '90210', 'kim.grace@company.com',        6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (6,  'James',    'Borg',     '688-655-5550', '450',  'Stone',       'Houston',      'TX', '90210', 'james.borg@company.com',       1, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (7,  'Alex',     'Freed',    '644-445-4000', '4333', 'Pillsbury',   'Milwaukee',    'WI', '90210', 'alex.freed@company.com',       7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (8,  'Evan',     'Wallis',   '622-225-2000', '134',  'Pelham',      'Milwaukee',    'WI', '90210', 'evan.wallis@company.com',      7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (9,  'Jared',    'James',    '611-115-1000', '123',  'Peachtree',   'Atlanta',      'GA', '90210', 'jared.james@company.com',      6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (10, 'John',     'James',    '555-555-5000', '7676', 'Bloomington', 'Sacramento',   'CA', '90210', 'john.james1@company.com',      6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (11, 'Andy',     'Vile',     '222-222-2020', '1967', 'Jordan',      'Milwaukee',    'WI', '90210', 'andy.vile@company.com',        7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (12, 'Brad',     'Knight',   '111-111-1030', '176',  'Main St.',    'Atlanta',      'GA', '90210', 'brad.knight@company.com',      6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (13, 'Josh',     'Zell',     '222-222-2010', '266',  'McGrady',     'Milwaukee',    'WI', '90210', 'josh.zell@company.com',        7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (14, 'Justin',   'Mark',     '111-111-1020', '2342', 'May',         'Atlanta',      'GA', '90210', 'justin.mark@company.com',      6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (15, 'Jon',      'Jones',    '111-111-1010', '111',  'Allgood',     'Atlanta',      'GA', '90210', 'jon.jones@company.com',        6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (16, 'Ahmad',    'Jabbar',   '987-987-9870', '980',  'Dallas',      'Houston',      'TX', '90210', 'ahmad.jabbar@company.com',     4, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (17, 'Joyce',    'English',  '453-453-4530', '5631', 'Rice',        'Houston',      'TX', '90210', 'joyce.english@company.com',    5, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (18, 'Ramesh',   'Narayan',  '666-884-4440', '971',  'Fire Oak',    'Humble',       'TX', '90210', 'ramesh.narayan@company.com',   5, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (19, 'Alicia',   'Zelaya',   '999-887-7770', '3321', 'Castle',      'Spring',       'TX', '90210', 'alicia.zelaya@company.com',    4, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (20, 'John',     'Smith',    '123-456-7890', '731',  'Fondren',     'Houston',      'TX', '90210', 'john.smith1@company.com',      5, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (21, 'Jennifer', 'Wallace',  '987-654-3210', '291',  'Berry',       'Bellaire',     'TX', '90210', 'jennifer.wallace@company.com', 4, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (22, 'Franklin', 'Wong',     '333-445-5550', '638',  'Voss',        'Houston',      'TX', '90210', 'franklin.wong@company.com',    5, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (23, 'Tom',      'Brand',    '222-222-2030', '112',  'Third St',    'Milwaukee',    'WI', '90210', 'tom.brand@company.com',        7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (24, 'Jenny',    'Vos',      '222-222-2040', '263',  'Mayberry',    'Milwaukee',    'WI', '90210', 'jenny.vos@company.com',        7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (25, 'Chris',    'Carter',   '222-222-2050', '565',  'Jordan',      'Milwaukee',    'WI', '90210', 'chris.carter@company.com',     7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (26, 'Jeff',     'Chase',    '333-333-3010', '145',  'Bradbury',    'Sacramento',   'CA', '90210', 'jeff.chase@company.com',       6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (27, 'Bonnie',   'Bays',     '444-444-4010', '111',  'Hollow',      'Milwaukee',    'WI', '90210', 'bonnie.bays@company.com',      7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (28, 'Alec',     'Best',     '444-444-4020', '233',  'Solid',       'Milwaukee',    'WI', '90210', 'alec.best@company.com',        7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (29, 'Sam',      'Snedden',  '444-444-4030', '987',  'Windy St',    'Milwaukee',    'WI', '90210', 'sam.snedden@company.com',      7, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (30, 'Nandita',  'Ball',     '555-555-5010', '222',  'Howard',      'Sacramento',   'CA', '90210', 'nandita.ball@company.com',     6, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (31, 'Jill',     'Jarvis',   '666-666-6010', '6234', 'Lincoln',     'Chicago',      'IL', '90210', 'jill.jarvis@company.com',      8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (32, 'Kate',     'King',     '666-666-6020', '1976', 'Boone Trace', 'Chicago',      'IL', '90210', 'kate.king@company.com',        8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (33, 'Lyle',     'Leslie',   '666-666-6030', '417',  'Hancock Ave', 'Chicago',      'IL', '90210', 'lyle.leslie@company.com',      8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (34, 'Billie',   'King',     '666-666-6040', '556',  'Washington',  'Chicago',      'IL', '90210', 'billie.king@company.com',      8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (35, 'Jon',      'Kramer',   '666-666-6050', '1988', 'Windy Creek', 'Seattle',      'WA', '90210', 'jon.kramer@company.com',       8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (36, 'Ray',      'King',     '666-666-6060', '213',  'Delk Road',   'Seattle',      'WA', '90210', 'ray.king@company.com',         8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (37, 'Gerald',   'Small',    '666-666-6070', '122',  'Ball Street', 'Dallas',       'TX', '90210', 'gerald.small@company.com',     8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (38, 'Arnold',   'Head',     '666-666-6080', '233',  'Spring St',   'Dallas',       'TX', '90210', 'arnold.head@company.com',      8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (39, 'Helga',    'Pataki',   '666-666-6090', '101',  'Holyoke St',  'Dallas',       'TX', '90210', 'helga.pataki@company.com',     8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (40, 'Naveen',   'Drew',     '666-666-6100', '198',  'Elm St',      'Philadelphia', 'PA', '90210', 'naveen.drew@company.com',      8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (41, 'Carl',     'Reedy',    '666-666-6110', '213',  'Ball St',     'Philadelphia', 'PA', '90210', 'carl.reedy@company.com',       8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (42, 'Sammy',    'Hall',     '666-666-6120', '433',  'Main Street', 'Miami',        'FL', '90210', 'sammy.hall@company.com',       8, CURRENT_TIMESTAMP);
INSERT INTO EMPLOYEE VALUES (43, 'Red',      'Bacher',   '666-666-6130', '196',  'Elm Street',  'Miami',        'FL', '90210', 'red.bacher@company.com',       8, CURRENT_TIMESTAMP);


-- INSERT INTO ROLE (Role_Id, Role_Name, Creation_Time) VALUES
INSERT INTO ROLES VALUES (1, 'Manager',     CURRENT_TIMESTAMP);
INSERT INTO ROLES VALUES (2, 'Technician',  CURRENT_TIMESTAMP);
INSERT INTO ROLES VALUES (3, 'Ticketing',   CURRENT_TIMESTAMP);
INSERT INTO ROLES VALUES (4, 'Concessions', CURRENT_TIMESTAMP);
INSERT INTO ROLES VALUES (5, 'Ushers',      CURRENT_TIMESTAMP);

-- INSERT INTO PERFORMS (Employee_Id, Role_Id, Creation_Time) VALUES
INSERT INTO PERFORMS VALUES (1,  1, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (2,  2, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (3,  3, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (4,  4, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (5,  5, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (6,  3, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (7,  4, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (8,  2, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (9,  5, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (10, 3, CURRENT_TIMESTAMP);
-- INSERT INTO PERFORMS VALUES (11, 1, CURRENT_TIMESTAMP);  -- Another manager (if you want it)
INSERT INTO PERFORMS VALUES (12, 4, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (13, 5, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (14, 2, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (15, 3, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (16, 4, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (17, 2, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (18, 5, CURRENT_TIMESTAMP);
INSERT INTO PERFORMS VALUES (19, 3, CURRENT_TIMESTAMP);
-- INSERT INTO PERFORMS VALUES (20, 1, NOW());  -- Manager


-- INSERT INTO RATING (Rate_Id, Rating) VALUES
INSERT INTO RATING VALUES (1, 'G'       , CURRENT_TIMESTAMP);
INSERT INTO RATING VALUES (2, 'PG'      , CURRENT_TIMESTAMP);
INSERT INTO RATING VALUES (3, 'PG-13'   , CURRENT_TIMESTAMP);
INSERT INTO RATING VALUES (4, 'R'       , CURRENT_TIMESTAMP);
INSERT INTO RATING VALUES (5, 'Unrated' , CURRENT_TIMESTAMP);

-- INSERT INTO GENRES (Genre_Id, Genre_type) VALUES
INSERT INTO GENRES VALUES (1, 'Action'      , CURRENT_TIMESTAMP );
INSERT INTO GENRES VALUES (2, 'Animation'   , CURRENT_TIMESTAMP );
INSERT INTO GENRES VALUES (3, 'Comedy'      , CURRENT_TIMESTAMP );
INSERT INTO GENRES VALUES (4, 'Famiy'       , CURRENT_TIMESTAMP );
INSERT INTO GENRES VALUES (5, 'Horror'      , CURRENT_TIMESTAMP );
INSERT INTO GENRES VALUES (6, 'Thriller'    , CURRENT_TIMESTAMP );


-- INSERT INTO MOVIE (Movie_Id, Title, Description, Year, Duration, Release_Date, Rate_Id) VALUES, 
INSERT INTO MOVIE VALUES ( 1, 'Skyfall',            'James Bond thriller',                              2012, 143, '2012-11-09', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 2, 'Interstellar',       'Space exploration epic',                           2014, 169, '2014-11-07', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 3, 'The Silent Horizon', 'A team uncovers an alien signal deep underground', 2020, 128, '2020-08-14', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 4, 'Crimson Dusk',       'A detective hunts a serial killer at sunset',      2019, 115, '2019-05-22', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 5, 'Frozen Empire',      'A kingdom battles eternal winter',                 2016, 102, '2016-12-02', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 6, 'Neon Nights',        'Cyberpunk thriller set in 2090',                   2021, 131, '2021-09-10', 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 7, 'The Last Frontier',  'A soldier survives behind enemy lines',            2013, 118, '2013-03-15', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 8, 'Emerald Tide',       'A treasure hunt inspired by old maps',             2018, 126, '2018-07-20', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES ( 9, 'Moonbreaker',        'Astronauts attempt the first moon colony',         2022, 150, '2022-11-18', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (10, 'Shadow Valley',      'A family moves into a mysterious rural town',      2017, 104, '2017-04-28', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (11, 'Iron Reborn',        'A hero rises in a post-apocalyptic wasteland',     2015, 122, '2015-05-08', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (12, 'The Ivory Tower',    'A professor uncovers a global conspiracy',         2010, 112, '2010-10-01', 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (13, 'Silver Arrow',       'A rogue archer leads a rebellion',                 2018, 119, '2018-06-29', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (14, 'Vortex Zero',        'Scientists accidentally open a time portal',       2020, 140, '2020-02-21', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (15, 'After The Storm',    'A town rebuilds after a massive hurricane',        2019, 108, '2019-09-06', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (16, 'Urban Pulse',        'Dance crews battle for city dominance',            2014,  98, '2014-07-18', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (17, 'Firecrest',          'A dragon awakens after centuries',                 2017, 133, '2017-03-10', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (18, 'The Glass Key',      'A journalist uncovers political corruption',       2011, 110, '2011-01-28', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (19, 'Winter Rose',        'Romantic drama set in snowy Vermont',              2013, 107, '2013-02-14', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (20, 'Deepline',           'Divers explore a sunken research facility',        2021, 147, '2021-10-08', 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (21, 'Solar Echo',         'Two worlds collide in a cosmic event',             2023, 152, '2023-05-19', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (22, 'Broken Kingdom',     'A prince returns to reclaim the throne',           2016, 124, '2016-09-30', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (23, 'Hollow Creek',       'A supernatural presence haunts a small town',      2012, 102, '2012-10-12', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (24, 'The Long Chase',     'A fugitive races across continents',               2014, 129, '2014-03-21', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (25, 'Crimson Orchid',     'A spy thriller involving a deadly bio-weapon',     2018, 132, '2018-11-09', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (26, 'Seven Shores',       'A group explores seven mythical islands',          2020, 141, '2020-07-03', 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (27, 'Clockwork Fate',     'A steampunk rebellion rises in old London',        2011, 118, '2011-06-10', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (28, 'Daybreakers',        'A zombie outbreak at dawn',                        2015, 109, '2015-10-30', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (29, 'Ruby Falls',         'A couple discovers dark secrets during vacation',  2017,  95, '2017-08-18', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (30, 'Sentinel One',       'A lone soldier defends the last outpost',          2019, 134, '2019-04-05', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (31, 'Orions Gate',        'A cosmic rift appears near Jupiter',               2022, 160, '2022-12-02', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (32, 'Silver Lining Run',  'Two friends road-trip across America',             2016, 105, '2016-04-29', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (33, 'Phantom Strike',     'Elite agents stop a massive terrorist plot',       2013, 123, '2013-06-14', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (34, 'Last Ember',         'A blacksmith discovers magical powers',            2021, 128, '2021-09-17', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (35, 'Mirage City',        'A detective solves crimes in a virtual world',     2020, 139, '2020-11-06', 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (36, 'Blue Raven',         'An assassin seeks redemption',                     2012, 111, '2012-05-11', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (37, 'The Painted Veil',   'An artist falls into a criminal web',              2014, 122, '2014-02-07', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (38, 'Stormvale',          'A coastal town braces for a superstorm',           2018, 116, '2018-09-14', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (39, 'Nightspire',         'A thief infiltrates a towering fortress',          2015, 130, '2015-01-16', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (40, 'Eternal Ashes',      'A dark fantasy tale of rebirth',                   2019, 144, '2019-12-13', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (41, 'Lunar Rift',         'A moon base faces catastrophic failure',           2023, 155, '2023-06-16', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (42, 'Paper Lanterns',     'Slice-of-life drama set in Japan',                 2017,  98, '2017-03-03', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (43, 'Fire in the Sky',    'Firefighters battle a citywide blaze',             2011, 114, '2011-08-26', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (44, 'Quantum Divide',     'Parallel worlds collide unexpectedly',             2020, 142, '2020-03-13', 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (45, 'Kingslayer',         'A warrior confronts a corrupt monarchy',           2018, 121, '2018-10-05', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (46, 'Velvet Echoes',      'A pianist unravels a haunting melody',             2014, 104, '2014-12-12', 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (47, 'The Fallen Star',    'An asteroid sighting changes everything',          2010, 101, '2010-05-14', 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (48, 'Rivers Edge',        'A missing person case near a quiet river',         2013, 108, '2013-07-12', 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (49, 'Gold Horizon',       'Prospectors search for a legendary vein',          2016, 125, '2016-11-04', 2, CURRENT_TIMESTAMP);
INSERT INTO MOVIE VALUES (50, 'Afterglow',          'A couple reconnects after years apart',            2019, 110, '2019-02-08', 5, CURRENT_TIMESTAMP);


-- INSERT INTO MOVIE_GENRE (Movie_Id, Genre_Id, Creation_Time) VALUES
INSERT INTO MOVIE_GENRE VALUES ( 1, 1, CURRENT_TIMESTAMP);  -- Skyfall - Action
INSERT INTO MOVIE_GENRE VALUES ( 1, 6, CURRENT_TIMESTAMP);  -- Thriller
INSERT INTO MOVIE_GENRE VALUES ( 2, 1, CURRENT_TIMESTAMP);  -- Interstellar - Action
INSERT INTO MOVIE_GENRE VALUES ( 2, 4, CURRENT_TIMESTAMP);  -- Family/Sci-Fi vibe
INSERT INTO MOVIE_GENRE VALUES ( 3, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 3, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 4, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 5, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 6, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 6, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 7, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 8, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 9, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES ( 9, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (10, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (11, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (12, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (13, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (14, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (14, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (15, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (16, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (16, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (17, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (17, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (18, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (19, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (19, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (20, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (21, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (21, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (22, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (23, 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (24, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (24, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (25, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (26, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (26, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (27, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (27, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (28, 5, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (29, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (29, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (30, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (31, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (31, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (32, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (32, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (33, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (34, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (34, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (35, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (36, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (37, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (37, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (38, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (39, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (40, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (40, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (41, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (41, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (42, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (42, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (43, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (44, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (44, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (45, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (46, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (46, 4, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (47, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (48, 6, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (49, 1, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (50, 3, CURRENT_TIMESTAMP);
INSERT INTO MOVIE_GENRE VALUES (50, 4, CURRENT_TIMESTAMP);


-- INSERT INTO SHOWS (Auditorium_Id, Movie_Id, Start_time, End_time, Format, Creation_Time) VALUES
INSERT INTO SHOWS VALUES (101, 1,  '2025-11-23 18:00:00', '2025-11-23 20:30:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (102, 2,  '2025-11-23 21:00:00', '2025-11-24 00:00:00', 'IMAX',     CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (103, 5,  '2025-11-24 13:00:00', '2025-11-24 14:45:00', '3D',       CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (104, 8,  '2025-11-24 15:30:00', '2025-11-24 17:30:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (105, 14, '2025-11-24 19:00:00', '2025-11-24 21:20:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (106, 22, '2025-11-25 16:00:00', '2025-11-25 18:10:00', 'IMAX',     CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (107, 19, '2025-11-25 18:30:00', '2025-11-25 20:20:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (108, 12, '2025-11-25 20:45:00', '2025-11-25 22:35:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (109, 32, '2025-11-26 11:00:00', '2025-11-26 12:50:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (110, 37, '2025-11-26 13:30:00', '2025-11-26 15:10:00', 'Thriller', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (111, 31, '2025-11-26 17:00:00', '2025-11-26 19:40:00', 'IMAX',     CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (112, 44, '2025-11-27 14:00:00', '2025-11-27 16:20:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (113, 45, '2025-11-27 17:00:00', '2025-11-27 19:05:00', 'IMAX',     CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (114, 38, '2025-11-27 19:30:00', '2025-11-27 21:25:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (115, 17, '2025-11-28 12:00:00', '2025-11-28 14:15:00', '3D',       CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (116, 26, '2025-11-28 14:45:00', '2025-11-28 17:05:00', 'IMAX',     CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (117, 29, '2025-11-28 18:00:00', '2025-11-28 19:35:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (118, 41, '2025-11-29 16:00:00', '2025-11-29 18:35:00', 'IMAX',     CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (119, 50, '2025-11-29 19:00:00', '2025-11-29 21:00:00', 'Standard', CURRENT_TIMESTAMP);
INSERT INTO SHOWS VALUES (120, 34, '2025-11-29 21:30:00', '2025-11-29 23:40:00', '3D',       CURRENT_TIMESTAMP);

INSERT INTO SHOWS VALUES
(101, 2, '2025-11-23 10:00:00', '2025-11-23 12:45:00', 'Standard', CURRENT_TIMESTAMP),
(101, 2, '2025-11-23 13:30:00', '2025-11-23 16:15:00', 'Standard', CURRENT_TIMESTAMP),
(101, 2, '2025-11-23 17:00:00', '2025-11-23 19:45:00', 'IMAX',     CURRENT_TIMESTAMP),
(101, 2, '2025-11-23 20:30:00', '2025-11-23 23:15:00', 'IMAX',     CURRENT_TIMESTAMP);
